# Generated by Django 3.0.11 on 2020-12-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201218_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aadhaar_no',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='aadhaar_no'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='phone_no'),
        ),
    ]
