# Generated by Django 3.0.11 on 2020-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201219_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='phone no.'),
        ),
    ]
